/*
 * BaaS API Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.baas.rest.module;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Body1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-12T03:32:15.669Z[GMT]")
public class Body1 {
  @JsonProperty("transaction")
  private Object transaction = null;

  @JsonProperty("oss_endpoint")
  private String ossEndpoint = null;

  @JsonProperty("oss_bucket")
  private String ossBucket = null;

  @JsonProperty("notary_id")
  private String notaryId = null;

  public Body1 transaction(Object transaction) {
    this.transaction = transaction;
    return this;
  }

   /**
   * Transaction object, same with query
   * @return transaction
  **/
  @Schema(required = true, description = "Transaction object, same with query")
  public Object getTransaction() {
    return transaction;
  }

  public void setTransaction(Object transaction) {
    this.transaction = transaction;
  }

  public Body1 ossEndpoint(String ossEndpoint) {
    this.ossEndpoint = ossEndpoint;
    return this;
  }

   /**
   * Your OSS endpoint
   * @return ossEndpoint
  **/
  @Schema(required = true, description = "Your OSS endpoint")
  public String getOssEndpoint() {
    return ossEndpoint;
  }

  public void setOssEndpoint(String ossEndpoint) {
    this.ossEndpoint = ossEndpoint;
  }

  public Body1 ossBucket(String ossBucket) {
    this.ossBucket = ossBucket;
    return this;
  }

   /**
   * Your OSS bucket name
   * @return ossBucket
  **/
  @Schema(required = true, description = "Your OSS bucket name")
  public String getOssBucket() {
    return ossBucket;
  }

  public void setOssBucket(String ossBucket) {
    this.ossBucket = ossBucket;
  }

  public Body1 notaryId(String notaryId) {
    this.notaryId = notaryId;
    return this;
  }

   /**
   * Notary id which returned by oss submit method
   * @return notaryId
  **/
  @Schema(required = true, description = "Notary id which returned by oss submit method")
  public String getNotaryId() {
    return notaryId;
  }

  public void setNotaryId(String notaryId) {
    this.notaryId = notaryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return Objects.equals(this.transaction, body1.transaction) &&
        Objects.equals(this.ossEndpoint, body1.ossEndpoint) &&
        Objects.equals(this.ossBucket, body1.ossBucket) &&
        Objects.equals(this.notaryId, body1.notaryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transaction, ossEndpoint, ossBucket, notaryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    ossEndpoint: ").append(toIndentedString(ossEndpoint)).append("\n");
    sb.append("    ossBucket: ").append(toIndentedString(ossBucket)).append("\n");
    sb.append("    notaryId: ").append(toIndentedString(notaryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
