/*
 * BaaS API Gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aliyun.baas.rest.module;

import java.util.Objects;
import java.util.Arrays;
import com.aliyun.baas.rest.module.Response;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InlineResponse2003Result
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-12T03:32:15.669Z[GMT]")
public class InlineResponse2003Result {
  @JsonProperty("response")
  private Response response = null;

  @JsonProperty("notary_id")
  private String notaryId = null;

  @JsonProperty("checksum")
  private String checksum = null;

  public InlineResponse2003Result response(Response response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @Schema(required = true, description = "")
  public Response getResponse() {
    return response;
  }

  public void setResponse(Response response) {
    this.response = response;
  }

  public InlineResponse2003Result notaryId(String notaryId) {
    this.notaryId = notaryId;
    return this;
  }

   /**
   * Notary id
   * @return notaryId
  **/
  @Schema(required = true, description = "Notary id")
  public String getNotaryId() {
    return notaryId;
  }

  public void setNotaryId(String notaryId) {
    this.notaryId = notaryId;
  }

  public InlineResponse2003Result checksum(String checksum) {
    this.checksum = checksum;
    return this;
  }

   /**
   * Object sha256 checksum in hex format
   * @return checksum
  **/
  @Schema(required = true, description = "Object sha256 checksum in hex format")
  public String getChecksum() {
    return checksum;
  }

  public void setChecksum(String checksum) {
    this.checksum = checksum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003Result inlineResponse2003Result = (InlineResponse2003Result) o;
    return Objects.equals(this.response, inlineResponse2003Result.response) &&
        Objects.equals(this.notaryId, inlineResponse2003Result.notaryId) &&
        Objects.equals(this.checksum, inlineResponse2003Result.checksum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, notaryId, checksum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003Result {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    notaryId: ").append(toIndentedString(notaryId)).append("\n");
    sb.append("    checksum: ").append(toIndentedString(checksum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
