/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body struct {
	// Transaction object, same with invoke
	Transaction Object `json:"transaction"`
	// Your OSS endpoint
	OssEndpoint string `json:"oss_endpoint"`
	// Your OSS bucket name
	OssBucket string `json:"oss_bucket"`
	// Object data
	Data string `json:"data"`
	// Optional, object file path in oss, gateway will save object in root directory with notary_id if this field is empty.
	OssPath string `json:"oss_path,omitempty"`
	// Optional, gateway will try to use this field as notary id if set.
	NotaryId string `json:"notary_id,omitempty"`
}
