/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2002 struct {
	// Boolean indicating if the request was successful.
	Success bool `json:"Success"`

	Result *Block `json:"Result"`

	Error_ *ModelError `json:"Error"`
}
