/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Transaction struct {
	// The id of the transaction
	Id string `json:"id,omitempty"`
	// The state of the transaction, VALID or INVALID
	State string `json:"state"`
	// Creator identity of the transaction. It's [MSPID].[username] in HyperLedger Fabric.
	From string `json:"from"`
	// The desitinition of the transaction. It's chaincode name in HyperLedger Fabric.
	To string `json:"to"`
	// The input data of the transaction. It's invoke arguments of chaincode in HyperLedger Fabric.
	Input string `json:"input"`
	// Real data of the transaction
	Data Object `json:"data,omitempty"`

	Events []Event `json:"events"`
}
