/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Response struct {
	// The id of the transaction
	Id string `json:"id"`
	// The status returned by contract
	Status string `json:"status,omitempty"`

	Event *Event `json:"event,omitempty"`
	// Real data of response
	Data []byte `json:"data"`
}
