/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Event struct {
	// The unique identifier for event
	Id string `json:"id"`
	// The id of the gateway instance
	InstanceId string `json:"instance_id"`
	// Network name. In hyperledger fabric, network name is channel name.
	Network string `json:"network"`

	Type_ *EventType `json:"type"`
	// The name of event
	Name string `json:"name"`
	// The data of event
	Content *interface{} `json:"content"`
}
