/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// EventType : The type of event
type EventType string

// List of EventType
const (
	TX EventType = "Tx"
	CONFIG EventType = "Config"
	CONTRACT EventType = "Contract"
	BLOCK EventType = "Block"
)
