/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body1 struct {
	// Transaction object, same with query
	Transaction Object `json:"transaction"`
	// Your OSS endpoint
	OssEndpoint string `json:"oss_endpoint"`
	// Your OSS bucket name
	OssBucket string `json:"oss_bucket"`
	// Notary id which returned by oss submit method
	NotaryId string `json:"notary_id"`
}
