/*
 * BaaS API Gateway
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Block struct {
	// The index(heigh) of the block
	Number int32 `json:"number"`
	// The hex encoded hash of the block
	Hash string `json:"hash"`
	// The hex encoded hash of the previous block
	PreviousHash string `json:"previous_hash"`
	// Block create time in unix timestamp
	CreateTime int32 `json:"create_time"`

	Transactions []string `json:"transactions"`
	// Real data of the transaction
	Data Object `json:"data,omitempty"`
}
